name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Test before release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luacov

      - name: Run tests
        run: busted --verbose

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create rockspec
        run: |
          cat > tupelo-${{ steps.get_version.outputs.VERSION }}-1.rockspec << EOF
          package = "tupelo"
          version = "${{ steps.get_version.outputs.VERSION }}-1"
          source = {
             url = "git+https://github.com/${{ github.repository }}.git",
             tag = "v${{ steps.get_version.outputs.VERSION }}"
          }
          description = {
             summary = "A functional programming library for Lua",
             detailed = "Tupelo brings modern type safety and functional programming concepts to Lua projects.",
             homepage = "https://github.com/${{ github.repository }}",
             license = "MIT"
          }
          dependencies = {
             "lua >= 5.1"
          }
          build = {
             type = "builtin",
             modules = {
                tupelo = "src/tupelo/init.lua"
             }
          }
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: tupelo-${{ steps.get_version.outputs.VERSION }}-1.rockspec
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
